### ISSUE TITLE
[Docs] Error Handling

### ISSUE THREAD

**Issue by th3fallen** [BetterTyped/hyper-fetch#16]
**Is your feature request related to a problem? Please describe.**
It would be great to have some documentation surrounding handling errors. particularly errors when not using the typical async/await syntax as currently i dont think .send will return a rejected promise. ( i could be wrong on that though)

**Comment by prc5** [comment]
@th3fallen Thanks for suggestion! We will add a better description for "send" method, describing it's usage and design.

To answer your question - no, it's not rejecting at any time. It always return tuple where first elememt is success response, second is an error and third is a status number.

`const [data, error, status] = await command.send()`
