### ISSUE TITLE
Dependent requests does not seem to be reactive

### ISSUE THREAD

**Issue by stefanullinger** [BetterTyped/hyper-fetch#22]
**Describe the bug**
In my NextJS application, I wanted to use the useFetch hook to fetch some data from the API. I needed to grab some URL parameter from the router. As this parameter was undefined during the first render cycle, I tried to set up some dependent request like it is shown in the [documentation](https://hyperfetch.bettertyped.com/guides/React/Dependent%20Requests).

```jsx
const DetailPage: NextPageWithLayout<DetailPageProps> = (props) => {
	const router = useRouter();
	const { postId } = router.query;

	const { data, loading, error } = useFetch(getPost.setParams({ postId }), {
		disabled: !postId
	});

	...

	return <div>...</div>;
}
```

Unfortunately the command I passed to useFetch was never executed, once the postId was ready.

**To Reproduce**
I have reproduced this behaviour in the following CodeSandbox:
https://codesandbox.io/s/hyper-fetch-usefetch-disabled-not-reactive-c4zfi8?file=/src/App.js

There is some `isFetchPostsDisabled` property that is set to false after 1 second, but the command does not get executed.
Maybe I am misunderstanding something?

I needed to work around this issue by creating some wrapper component, that I only include once the `isFetchPostsDisabled` is set to false, but this is not a real dependent request anymore.
https://codesandbox.io/s/hyper-fetch-usefetch-disabled-not-reactive-fixed-using-a-middleware-component-7mq6bj?file=/src/App.js

**Expected behavior**
Once the "disabled" property turns to `false`, I expect the command to be executed.

I was hoping you could help me a bit here.
Maybe I am misunderstanding something?

Regards,
Stefan

**Comment by prc5** [comment]
Hey Stefan, sorry to hear that this functionality did not work correctly for you. We will take a look at this issue and get back to you soon with a fix. Thanks for the report and reproduction example, we appreciate it a lot!

**Comment by prc5** [comment]
@stefanullinger Issue is solved, it was a victim of refactoring I did some time ago. Also please notice that we changed the library namespace from @better-typed to @hyper-fetch for some clarity and readability, so the installation and usage of it will be like this:
```tsx
import { Builder } from "@hyper-fetch/core";
import { useFetch } from "@hyper-fetch/react";
```

Have fun with HF!

**Comment by stefanullinger** [comment]
Nice, works perfectly now! Thanks a lot!
