### ISSUE TITLE
Typescript build error when using setDataMapper and trying to set dynamic data in submit function

### ISSUE THREAD

**Issue by stefanullinger** [BetterTyped/hyper-fetch#27]
Hey, in a TypeScript project I was following the Data Mapping Guide (https://hyperfetch.bettertyped.com/guides/Basic/Data%20Mapping/#set-payload-data-mapper) to transform some data into FormData.

I need to do it dynamically, so I also followed the Passing data and params guide (https://hyperfetch.bettertyped.com/docs/React/useSubmit/#passing-data-and-params) and tried to add my data to the submit function of the useSubmit hook.

But I am running in a TypeScript build error.
Can you assist in any way? What am I doing wrong?

```Type 'string' is not assignable to type 'never'.ts(2322)```

I prepared some CodeSandbox here: https://codesandbox.io/s/hyper-fetch-setdatamapper-dynamic-params-pekl0p?file=/src/App.tsx:714-726

Thanks in advance!
Stefan

**Comment by prc5** [comment]
Hey @stefanullinger, I believe it is solved in the new version(v1.7.1), thank you for reporting!
