### ISSUE TITLE
Not working with Sveltekit

### ISSUE THREAD

**Issue by Jedliu** [BetterTyped/hyper-fetch#39]
**Describe the bug**
Not working with SvelteKit.

**To Reproduce**
1. Go to [this repository on stackblitz](https://stackblitz.com/edit/sveltejs-kit-template-default-44feca?file=src%2Froutes%2F%2Bpage.js)
2. Check the error in the browser console
```
TypeError: import_events4.default is not a constructor
```
3. Uncomment this code in `page.js`
```
// const [data, error, status] = await getData.send();
```
4. New error occurs in terminal
```
ReferenceError: window is not defined
```

**Screenshots**
![hyper-fetch](https://user-images.githubusercontent.com/771703/215751672-d1bdc8b3-a985-4124-b345-4aa66d5e4ee5.jpg)

**Additional context**
There are few demos and the documents is not sufficient to start working with. Thank you!

**Comment by prc5** [comment]
@Jedliu The same thing as in #42 . We are going to solve it today or tomorrow. Thanks for support!

**Comment by prc5** [comment]
@Jedliu Released update, should be good now 👍🏻 I'm looking forward to some feedback! 😄

**Comment by Jedliu** [comment]
This works like a charm. Thanks!
