### ISSUE TITLE
Settings for Increasing the request default timeout (default adapter)

### ISSUE THREAD

**Issue by johngerome** [BetterTyped/hyper-fetch#44]
**Is your feature request related to a problem? Please describe.**
Hi, I've noticed that a request get cancelled If it takes more than 5 seconds to response.
Can't find the correct configuration for this one [here](https://github.com/BetterTyped/hyper-fetch/blob/5f8a7d7/packages/core/src/request/request.ts#L91).

**Is there any way I can increase the default timeout ?**

In the browser adapter (even on the server), I can see the default timeout but I'm not really sure If this is the reason. https://github.com/BetterTyped/hyper-fetch/blob/ef4e3acc93f39de0ae7b742ceb46c66e859f438d/packages/core/src/adapter/adapter.browser.ts#L26

Any help would be much appreciated. Thank you.

**Comment by johngerome** [comment]
**Update**

Apparently I can override the timeout per request e.g. which solves my problem.

```js
getUsers: client.createRequest()({
    endpoint: `/users`,
    options: {
        timeout: DateInterval.minute * 1,
   },
})
```

Not sure if It would be good to override the timeout in the Client as well ?

**Comment by prc5** [comment]
@johngerome This is correct! We can set it globally on the Client with default options (setRequestDefaultOptions) or we can adjust it for particular Request with options property directly. I will add section to the docs Explaining this. 🙏👍

**Comment by johngerome** [comment]
@prc5 Perfect! Thank you so much.
