### ISSUE TITLE
setQueryParams doesn't support nested object

### ISSUE THREAD

**Issue by johngerome** [BetterTyped/hyper-fetch#50]
**Describe the bug**
Hi, Is it possible to support nested object on `setQueryParams ` without using JSON.stringify by default?
Or this is not a good practice?

Here's the example results when nested object was passed
```
filter: [object Object]
```

Any help would be much appreciated. Thank you.

**To Reproduce**
1. Go to https://stackblitz.com/edit/hyperfetch-nuxt-demo-xhr9qg?file=pages%2Findex.vue
2. Click on Fetch button
3. Open inspect element 
4. See Network tab > Fetch/XHR
5. Find repositories request
6. Check its Payload

**Expected behavior**
Display the actual object not [object Object]

**Comment by prc5** [comment]
Hey @johngerome, actually that would be cool to handle. I will try to add it in upcoming 4.0 👍🏻 As for now, JSON.stringify is probably the best way. As for being good practice or not - I think this really depends, but it's something that can be decided on the implementation stage, but I will to make it flexible in this area 😅
