### ISSUE TITLE
Issue with typescript/vscode finding types

### ISSUE THREAD

**Issue by Darkle** [BetterTyped/hyper-fetch#71]
**Describe the bug**
Issue with typescript/vscode finding types

**To Reproduce**
After installing via: `npm i @hyper-fetch/core`, I get the following error message in vscode:

![vsc](https://github.com/BetterTyped/hyper-fetch/assets/6868833/5a84d7e7-61db-4535-b1f4-62761f088296)

Looking at the hyper-fecth package.json after installation, the exports section looks like this:
```json
  "exports": {
    ".": {
      "types": {
        "import": "./index.d.ts"
      },
      "browser": {
        "require": "./dist/browser/index.cjs.js",
        "import": "./dist/browser/index.esm.js"
      },
      "default": {
        "require": "./dist/index.cjs.js",
        "import": "./dist/index.esm.js"
      }
    },
    "./package.json": "./package.json"
  },
```
It looks like `"import": "./index.d.ts"` should in fact be `"import": "./dist/index.d.ts"`

**Expected behavior**
It should find the types.

**Desktop (please complete the following information):**
 - OS: Debian Bullseye
 - Browser NA
 - Version 5.7.1

**Comment by stefanullinger** [comment]
Hi, I am running into the same issue right now.
