### ISSUE TITLE
419 status with laravel breeze and nuxt

### ISSUE THREAD

**Issue by natarajbodhi** [BetterTyped/hyper-fetch#73]
**Describe the bug**
I'm trying to use HyperFetch in one my projects. When I use the code below trying to login I get 419 unknown status. But it is working fine with axios and nuxt's useFetch. 

**To Reproduce**
	async function handleLogin() {
		const client = new Client({ url: "http://localhost:8000" });

		const cookie = client.createRequest()({
			endpoint: "/sanctum/csrf-cookie",
			method: "GET",
			options: { withCredentials: true },
		});
		await cookie.send();

		const token = useCookie("XSRF-TOKEN");

		type ResponseType = { token: string; refreshToken: string };
		type RequestType = { email: string; password: string };

		const postLogin = client.createRequest<ResponseType, RequestType>()({
			method: "POST",
			endpoint: "/login",
			headers: {
				["X-XSRF-TOKEN"]: String(token.value),
			},
		});
    
		const { data, error, status } = await postLogin.send({
			data: {
				email: loginForm.email,
				password: loginForm.password,
			},
		});

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by johngerome** [comment]
Not a hyper-fetch issue I think.
You don't need to call `/sanctum/csrf-cookie` every login (submit).

>  subsequent requests to the Laravel application may receive 401 or 419 HTTP error response
@see https://laravel.com/docs/10.x/sanctum#logging-in

**Comment by prc5** [comment]
Thanks @johngerome for help! 🚀  
I will close the issue, if it still exist - I will reopen thread.
