### ISSUE TITLE
`useFetch` doesn't use `initialData`

### ISSUE THREAD

**Issue by jmas** [BetterTyped/hyper-fetch#93]
**Describe the bug**
I pass option `initialData: []`, but `useFetch` returns `null`.

**To Reproduce**
1. Create request
2. Pass request to `useFetch` and put `{ initialData: [] as any }`
3. Run `useFetch` and see that `data = null`

**Expected behavior**
I expect that `useFetch` will pass `initialData` as data if request is loading.

**Additional context**
Request:
```js
import client from "../../client";

type ResponseType = { id: number; name: string }[];

export default client.createRequest<ResponseType>()({
    endpoint: "/feeds",
    method: "GET",
});

```

`useFetch`:
```js
const { data } = useFetch(
    feedsIndex.setQueryParams({ with_user_feed: withUserFeed ? "1" : "0" }),
    { initialData: [] as any },
);

console.log(data); // null
```

**Comment by jmas** [comment]
I got the idea of `initialData`. It sets not only `data`, but also other `useFetch` return data. So I need to use it in following way:

```js
const { data } = useFetch(
    feedsIndex.setQueryParams({ with_user_feed: withUserFeed ? "1" : "0" }),
    { initialData: {
      data: []
    } },
);

console.log(data); // []
```

And now it works.

**Comment by prc5** [comment]
@jmas thanks for the issue! You're completely right, the "initialData" is misleading as there is more that can be inserted at initial render.
I will figure out a better approach maybe: `initialResponse` will work better 👍🏻

**Comment by jmas** [comment]
Hello, nice! I found that it lack of docs or examples about this option. The actual name confuse because React Query use initialData for storing data values.

initialResponse looks more convenient.

Thanks!
